In [1]:
import pandas as pd
import numpy as np

In [2]:
# Our features:
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

# Desired output:
y=np.array([[1],[1],[0]])

In [3]:
#Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))


#Derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)

In [4]:
X

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [5]:
y

array([[1],
       [1],
       [0]])

In [6]:
#Variable initialization
epoch=5000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

In [10]:
#weight and bias initialization

# For INPUT LAYER
# Weights of shape -> [4(#features) x 3(#hidden-layer nodes)]
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
# Bias of shape -> (1 x 3(#hidden-layer nodes))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))

# For HIDDEN-LAYER
# Weights of shape -> (3(#hidden-layer nodes) x 1 (#output neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
# Bias of shape -> (1 x 1(# Output neurons))
bout=np.random.uniform(size=(1,output_neurons))

In [11]:
bh

array([[0.55053093, 0.73500359, 0.97592017]])

In [12]:
for i in range(epoch):
    #Forward Propogation
    hidden_layer_input1=np.dot(X,wh)
    hidden_layer_input=hidden_layer_input1 + bh
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    output_layer_input1=np.dot(hiddenlayer_activations,wout)
    output_layer_input= output_layer_input1+ bout
    output = sigmoid(output_layer_input)

    #Backpropagation
    D = y-output
    slope_output_layer = derivatives_sigmoid(output)
    slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
    d_output = D * slope_output_layer
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += hiddenlayer_activations.T.dot(d_output) *lr
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    wh += X.T.dot(d_hiddenlayer) *lr
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr

In [13]:
print(output)

[[0.96721939]
 [0.95957678]
 [0.05718734]]
