In [1]:
import pandas as pd
import numpy as np

# Neural Network Review - 06/07/20
### Andrey Novichkov

## What is a Neural Network?

- This is a computational system inspired by structure, processing method and learning ability similar to our human brain  

A Neural Network is made up of 3 unique types of structures: **Inputs**, **Hidden Layers** and **Outputs**.  

**Inputs**: Are what is given to the network  
**Outputs**: What comes out of the neural network  
**Hidden Layers**: These are layers of sometimes multiple nodes, where each node is a **perceptron**.  
**Perceptron**: This is a node that mimics a neuron in the human body.   

### What is a Perceptron:
It is made out of several parts: **Inputs** + **Weights** -> **Summation and Bias** -> **Activation f(x)** -> **1 output**  
  
**Summation and Bias**: This is the function that combines inputs and weights  
**Activation f(x)**: A function that determines the output, could be a threshold function, but could be something else


### Forward and Backward Propagation
When we want the neural net to make a prediction, we give it some input, which runs through the input layer, the hidden layer(s) and is presented as output via the output layer, this process is called **forward propagation**  
  
When we get the output layer, we compare that result to the actual answer. This step is usually defined by a **cost function**, and we want our neural net to have as small of an error as possible  
  
We then run back through the neural net and update our weights(gradient descent) in order to minimize that cost function. This process is called **back propagation**

## Let's implement a very simple Neural Net ourselves, and see the steps in action

In [12]:
# Input array
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

# Output array
y=np.array([[1],[1],[0]])

# Sigmoid Function
# This is to introduce non-linearity to the activation function (output of NN)
def sigmoid (x):
    return 1/(1 + np.exp(-x))

# Derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)

**Now let's initialize the variables we need to build our neural network**  
We are only going to have 1 hidden layer here

In [9]:
# Training iterations
epoch=5000 
# Setting learning rate
lr=0.1 
# Number of features = number of inputs into NN = # columns in dataset
inputlayer_neurons = X.shape[1] 
# How many hidden layer neurons we have. This is defined by us
hiddenlayer_neurons = 3
# Number of outputs. This is also defined by us and the dataset we have
output_neurons = 1 

**Now we need to initialize weights and bias' for the NN**

In [15]:
# For input to HIDDEN layer
wh = np.random.uniform(size=(inputlayer_neurons, hiddenlayer_neurons))
bh = np.random.uniform(size=(1, hiddenlayer_neurons))

print(f'wh: {wh}')
print(f'bh: {bh}')

wh: [[0.66571579 0.89040976 0.48733742]
 [0.96375525 0.10898274 0.30842886]
 [0.00141498 0.07281419 0.55748999]
 [0.61820128 0.59712594 0.61647234]]
bh: [[0.41379415 0.79752472 0.5068145 ]]


In [16]:
# For input to OUTPUT layer
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

print(f'wout: {wout}')
print(f'bout: {bout}')

wout: [[0.6907534 ]
 [0.98427091]
 [0.54267795]]
bout: [[0.64192893]]


**Now we are ready for the training part**  
Again, this consists of forward and backward propagation

In [20]:
for i in range(epoch):
    # Forward Propagation
    # Input Layer
    hidden_layer_input = np.dot(X, wh)
    hidden_layer_input = hidden_layer_input + bh
    hidden_layer_activations = sigmoid(hidden_layer_input)

    # Hidden Layer
    output_layer_input = np.dot(hidden_layer_activations, wout)
    output_layer_input = output_layer_input + bout
    output = sigmoid(output_layer_input)

    # Backward Propagation - Optimizing cost function -> Read more about this
    error = y - output

    slope_output_layer = derivatives_sigmoid(output)
    slope_hidden_layer = derivatives_sigmoid(hidden_layer_activations)

    d_output = error * slope_output_layer
    d_hidden_layer = d_output.dot(wout.T) * slope_hidden_layer

    wout += hidden_layer_activations.T.dot(d_output) * lr
    bout += np.sum(d_output, axis=0, keepdims=True) * lr

    wh += X.T.dot(d_hidden_layer) * lr
    bh += np.sum(d_hidden_layer, axis=0, keepdims=True) * lr

In [23]:
print(f'Correct output: {y}')

Correct output: [[1]
 [1]
 [0]]


In [ ]:
print(f'Outp')